# config.py
import pygame


WINDOW_SIZE = 1000
BOARD_SIZE = 8
GAME_ONLINE = True
TILE_SIZE = WINDOW_SIZE / BOARD_SIZE
SIZE = (WINDOW_SIZE, WINDOW_SIZE)
DEPTH = 3
DISCONNECT_MSG = "DISCONNECT!"
BUFFER_SIZE = 2048
SERVER_ADDRESS = ("10.100.102.33", 12345)
